import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp } from '../server.mjs';

async function setup(t){const dir=mkdtempSync(path.join(tmpdir(),'vpan-test-'));const server=createApp({dbPath:path.join(dir,'app.sqlite'),adminToken:'unit-test-secret-long-enough',allowedOrigin:'http://localhost:1234'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true})});return `http://127.0.0.1:${server.address().port}`}
const payload=()=>({requestId:crypto.randomUUID(),role:'affiliate',markets:['Ghana'],name:'Test Partner',email:'test@example.com',company:'Example',telegram:'@test',message:'Experienced trader teams'});

test('homepage, markets and SPA fallback are served',async t=>{const base=await setup(t);for(const p of ['/','/markets','/markets/ghana','/apply']){const r=await fetch(base+p);assert.equal(r.status,200);assert.match(await r.text(),/PAN — Private Affiliate Network/)}const img=await fetch(base+'/assets/hero-king.webp');assert.equal(img.status,200);assert.equal(img.headers.get('content-type'),'image/webp')});
test('applications save, are idempotent and require validation',async t=>{const base=await setup(t);const b=payload();const send=x=>fetch(base+'/api/apply',{method:'POST',headers:{'Content-Type':'application/json','Origin':'http://localhost:1234'},body:JSON.stringify(x)});let r=await send(b);assert.equal(r.status,201);const j=await r.json();assert.match(j.reference,/^PAN-\d{4}-[A-F0-9]{8}$/);r=await send(b);assert.equal(r.status,200);assert.equal((await r.json()).reference,j.reference);r=await send({...payload(),email:'nope'});assert.equal(r.status,422);r=await fetch(base+'/api/apply',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://evil.example'},body:JSON.stringify(payload())});assert.equal(r.status,403)});
test('admin access is protected, can review and change status',async t=>{const base=await setup(t);await fetch(base+'/api/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});let r=await fetch(base+'/api/admin/applications');assert.equal(r.status,401);r=await fetch(base+'/api/admin/applications',{headers:{Authorization:'Bearer unit-test-secret-long-enough'}});assert.equal(r.status,200);const rows=(await r.json()).items;assert.equal(rows.length,1);r=await fetch(base+'/api/admin/applications/'+rows[0].id,{method:'PATCH',headers:{Authorization:'Bearer unit-test-secret-long-enough','Content-Type':'application/json'},body:JSON.stringify({status:'qualified'})});assert.equal(r.status,200);r=await fetch(base+'/api/admin/applications',{headers:{Authorization:'Bearer unit-test-secret-long-enough'}});assert.equal((await r.json()).items[0].status,'qualified')});