// Reviewed editorial inputs. These describe infrastructure and preparation, not PAN capacity.
export const sources = [
  {
    id: 'npci',
    name: 'NPCI — UPI merchant FAQ',
    url: 'https://www.npci.org.in/what-we-do/upi/faqs',
    markers: ['upi', 'merchant'],
    facts:
      'UPI is developed by NPCI. Merchant acceptance involves an acquiring bank. Business category and merchant identifiers are part of onboarding.',
    checked: '2026-10-09',
  },
  {
    id: 'daraja',
    name: 'Safaricom — Daraja API catalogue',
    url: 'https://developer.safaricom.co.ke/apis',
    markers: ['daraja', 'api'],
    facts:
      'Daraja exposes M-Pesa integration APIs. Its catalogue distinguishes authorization, customer-to-business collection and business-to-customer disbursement.',
    checked: '2026-10-09',
  },
  {
    id: 'spei',
    name: 'Banco de México — SPEI',
    url: 'https://www.banxico.org.mx/services/interbanking-electronic-payme.html',
    markers: ['spei', 'banco'],
    facts:
      'Banco de México operates SPEI, an interbank electronic transfer system. Payment reference and transfer information are used when investigating a transfer.',
    checked: '2026-10-09',
  },
];
const section = (id, heading, headingRu, body, bodyRu, bullets = [], bulletsRu = []) => ({
  id,
  heading,
  headingRu,
  body,
  bodyRu,
  bullets,
  bulletsRu,
});
const base = (
  slug,
  title,
  titleRu,
  summary,
  summaryRu,
  role,
  market,
  sourceIds,
  sections,
  checklist,
  checklistRu,
  initial = false,
) => ({
  slug,
  title,
  titleRu,
  summary,
  summaryRu,
  role,
  market,
  sourceIds,
  sections,
  checklist,
  checklistRu,
  initial,
  kind: 'guide',
  author: 'PAN Research',
  generated: false,
});

export const catalog = [
  base(
    'payment-partner-evaluation',
    'Evaluating a payment partner: evidence before integration',
    'Как оценить платёжного партнёра до интеграции',
    'A working brief for checking responsibilities, collection, settlement, reconciliation and incident handling with a prospective PSP or local team.',
    'Практический бриф для проверки ответственности, приёма платежей, расчётов, сверки и обработки инцидентов у PSP или локальной команды.',
    'provider',
    '',
    ['daraja', 'npci', 'spei'],
    [
      section(
        'scope',
        'Define the operating scope',
        'Определите границы работы',
        'Begin with a specific flow rather than a country name. Describe who pays, who receives, the currency, the business category and the contracting entity. A payment method being present in a country does not establish a provider’s ability to support your business. Ask the partner to identify the entity responsible for each part of the flow and provide evidence relevant to that role. Record unknowns explicitly in the brief so the commercial discussion does not turn assumptions into promises.',
        'Начните с конкретного потока: кто платит, кто получает средства, валюта, категория бизнеса и сторона договора. Наличие метода в стране не подтверждает возможность провайдера обслуживать ваш бизнес. Попросите партнёра назвать ответственную сторону для каждого этапа и предоставить относящиеся к её роли подтверждения. Неизвестные условия отмечайте прямо в брифе, чтобы предположения не превратились в обещания.',
        [
          'Contracting entity and operating role',
          'Supported business category confirmed in writing',
          'Collection, payouts and settlement described separately',
        ],
        [
          'Сторона договора и её операционная роль',
          'Категория бизнеса подтверждена письменно',
          'Приём, выплаты и расчёты описаны отдельно',
        ],
      ),
      section(
        'integration',
        'Ask for a demonstrable payment lifecycle',
        'Проверьте жизненный цикл платежа',
        'Request a walkthrough from payment creation to final status. Discuss authentication, transaction identifiers, callbacks, duplicate requests, retries, reversals and status queries. Safaricom’s Daraja catalogue distinguishes collection and disbursement APIs; that distinction is a useful reminder to test each required flow independently. Use synthetic transactions in an agreed test environment. Document which party decides the final state when an API response, callback and reconciliation report disagree.',
        'Попросите показать путь от создания платежа до конечного статуса: авторизацию, идентификаторы, уведомления, повторные запросы, возвраты и проверку состояния. В каталоге Daraja отдельно представлены приём и выплаты; каждый нужный поток стоит проверять самостоятельно. Используйте тестовые операции в согласованной среде. Зафиксируйте, кто определяет итоговый статус при расхождении ответа API, уведомления и отчёта сверки.',
      ),
      section(
        'operations',
        'Separate payment success from commercial settlement',
        'Отделите успешный платёж от расчётов',
        'A successful customer payment is only one part of the operating relationship. Ask how funds move to the agreed recipient, which records explain adjustments, and how exceptions are reconciled. Define report fields, export format, reporting timezone and a contact for disputed entries. Agree incident ownership and a communication path before production. PAN can receive a partner introduction and review the proposed fit; availability, pricing and operating commitments require a separate discussion with the relevant parties.',
        'Успешный платёж клиента — только часть отношений. Уточните движение средств к согласованному получателю, учёт корректировок и сверку исключений. Определите поля отчёта, формат выгрузки, часовой пояс и контакт по спорным операциям. До запуска согласуйте ответственность за инциденты и канал связи. PAN принимает знакомства и рассматривает подходящие варианты; доступность, стоимость и обязательства обсуждаются отдельно.',
      ),
    ],
    [
      'Write down the contracting entity and exact flow.',
      'Request category-specific confirmation.',
      'Test success, pending, duplicate and failed transactions.',
      'Compare a payment record with a settlement report.',
      'Agree an incident owner and escalation path.',
    ],
    [
      'Укажите сторону договора и точный поток.',
      'Получите подтверждение для своей категории.',
      'Проверьте успешные, ожидающие, повторные и неуспешные операции.',
      'Сопоставьте платёж и отчёт расчётов.',
      'Согласуйте ответственного за инциденты.',
    ],
    true,
  ),
  base(
    'affiliate-introduction-brief',
    'A useful affiliate introduction: prepare a brief both sides can act on',
    'Рекомендация аффилиата: бриф, с которым можно работать',
    'What to collect before introducing a PSP, payment team or merchant, and how to separate contact ownership from commercial outcomes.',
    'Что собрать до знакомства с PSP, командой или мерчантом и как согласовать авторство рекомендации и коммерческий результат.',
    'affiliate',
    '',
    [],
    [
      section(
        'fit',
        'Explain the reason for the introduction',
        'Объясните пользу знакомства',
        'Describe the partner’s role, markets, methods and the concrete reason for the connection. A useful introduction tells each side what a first conversation could resolve. Check that the contact is the right person to discuss the opportunity and that they expect the introduction. Avoid circulating someone’s personal details across an open group. A short, accurate brief makes it easier to decide whether to arrange a conversation and what additional information is needed.',
        'Опишите роль партнёра, страны, методы и конкретную причину знакомства. Полезная рекомендация объясняет обеим сторонам, что можно решить на первом разговоре. Проверьте, что контакт отвечает за нужное направление и ожидает знакомства. Личные данные не стоит распространять в открытой группе. Краткий точный бриф помогает решить, нужен ли разговор и какая информация ещё требуется.',
        [
          'Role and decision-making responsibility',
          'Markets and payment methods actually discussed',
          'A concrete requirement or capability',
          'Permission to share contact details',
        ],
        [
          'Роль и полномочия контакта',
          'Реальные страны и методы',
          'Конкретная потребность или возможность',
          'Согласие на передачу контакта',
        ],
      ),
      section(
        'attribution',
        'Agree attribution before sharing the contact',
        'Согласуйте авторство заранее',
        'Contact attribution and remuneration are separate questions. Establish what counts as a new introduction, how existing relationships are handled, and which evidence records the introduction. If compensation is offered, the agreement should identify the qualifying outcome, the responsible party and the conditions for calculation. Do not assume that submitting a form creates a commission entitlement. PAN’s affiliate entry invites a discussion of attribution and individual terms before introductions are made.',
        'Авторство контакта и вознаграждение — разные вопросы. Определите, что считается новым знакомством, как обрабатываются существующие связи и что подтверждает рекомендацию. Если предусмотрено вознаграждение, согласуйте результат, ответственную сторону и условия расчёта. Отправка формы сама по себе не создаёт право на комиссию. Условия и авторство рекомендации PAN предлагает обсуждать до знакомства.',
      ),
      section(
        'handover',
        'Make the handover specific',
        'Сделайте передачу конкретной',
        'Identify the next action, the owner of that action and the information required to proceed. Ask for a status update at an agreed point instead of repeatedly forwarding the same contact. Keep an introduction reference and note whether the contact was accepted, required more context or was outside the current scope. Share only information that is relevant to the proposed relationship. The PAN application accepts role, markets, company and a message; use the message to explain fit rather than to imply an unconfirmed deal.',
        'Определите следующий шаг, ответственного и необходимые сведения. Согласуйте момент обновления статуса, чтобы не пересылать один контакт повторно. Сохраняйте номер обращения и причину принятия, уточнения или отказа. Передавайте сведения, относящиеся к предполагаемым отношениям. В заявке PAN укажите роль, рынки, компанию и пользу знакомства; неподтверждённую сделку не стоит представлять как состоявшуюся.',
      ),
    ],
    [
      'Confirm the contact expects an introduction.',
      'Describe the business fit in one paragraph.',
      'Agree how existing contacts are handled.',
      'Document individual compensation terms if applicable.',
      'Keep the introduction reference and next action.',
    ],
    [
      'Подтвердите, что контакт ждёт знакомства.',
      'Опишите пользу в одном абзаце.',
      'Согласуйте обработку существующих контактов.',
      'Зафиксируйте условия вознаграждения, если оно предусмотрено.',
      'Сохраните номер обращения и следующий шаг.',
    ],
    true,
  ),
  base(
    'payment-reconciliation-checklist',
    'Payment reconciliation: a checklist for a first PSP discussion',
    'Сверка платежей: что обсудить с PSP',
    'Prepare transaction identifiers, exception handling and report requirements before connecting a payment flow.',
    'Подготовьте идентификаторы операций, обработку исключений и требования к отчётам до подключения платежей.',
    'merchant',
    '',
    ['spei', 'daraja'],
    [
      section(
        'identifiers',
        'Establish a shared transaction identity',
        'Согласуйте идентификаторы',
        'Map the merchant order, provider transaction, payment-method reference and settlement entry. Ask which identifiers are stable across retries and which change when a new attempt is created. Record the reporting timezone and currency for every report. Banco de México’s SPEI guidance describes transfer information used to investigate a payment; the practical question for your provider is how that evidence maps back to your own order. Use an example with fictitious details during the first discussion.',
        'Свяжите заказ мерчанта, операцию провайдера, идентификатор платёжного метода и запись расчётов. Уточните, какие значения сохраняются при повторе и какие меняются при новой попытке. Зафиксируйте валюту и часовой пояс отчётов. В документации SPEI описаны данные для поиска перевода; у провайдера нужно выяснить, как они связываются с вашим заказом. Для обсуждения используйте вымышленные тестовые реквизиты.',
      ),
      section(
        'exceptions',
        'Walk through exceptions, not only successful payments',
        'Проверьте исключения',
        'Agree what happens when a callback is delayed, a transaction remains pending, a customer retries, or a report arrives after the daily close. Decide who can change a final status and what evidence is required. A retry of the same instruction and a new customer payment must be distinguishable. Request a documented route for reversals, disputes and missing records. Keep a separate record of adjustments so that a resolved exception does not silently rewrite the original payment history.',
        'Обсудите задержку уведомления, ожидающий статус, повтор клиента и отчёт после закрытия дня. Определите, кто вправе менять конечный статус и на каком основании. Повтор одной инструкции должен отличаться от нового платежа. Запросите порядок возвратов, споров и поиска записей. Корректировки учитывайте отдельно, чтобы разрешение исключения не переписывало исходную историю без объяснения.',
      ),
      section(
        'handoff',
        'Define the operating handoff',
        'Определите операционный процесс',
        'Specify the export format, delivery mechanism, access permissions and escalation contact. Request a sample containing success, pending, failed and adjusted records. Reconcile gross amounts, fees and final settlement separately under the actual agreement. In your PAN merchant brief, identify the markets, payment methods and the reporting problem you are trying to solve. This helps establish a relevant introduction; it does not imply that a provider’s commercial or technical commitments are already confirmed.',
        'Определите формат и способ получения выгрузки, права доступа и контакт для эскалации. Запросите пример с успешными, ожидающими, неуспешными и исправленными записями. Суммы платежей, комиссии и итоговые расчёты сверяйте отдельно по действительному соглашению. В брифе для PAN опишите страны, методы и проблему отчётности. Это помогает подготовить знакомство и не заменяет подтверждение обязательств провайдера.',
      ),
    ],
    [
      'Map order, provider and payment-method IDs.',
      'Agree timezone and reporting cutoff.',
      'Test pending, duplicate and reversal cases.',
      'Request a sample export and adjustment history.',
      'Name the owner of unresolved differences.',
    ],
    [
      'Свяжите идентификаторы заказа, провайдера и метода.',
      'Согласуйте часовой пояс и время закрытия.',
      'Проверьте ожидание, повторы и возвраты.',
      'Запросите выгрузку и историю корректировок.',
      'Назначьте ответственного за расхождения.',
    ],
    true,
  ),
  base(
    'upi-partner-onboarding-brief',
    'UPI partner onboarding: what to put in an India payment brief',
    'Подключение UPI: что включить в бриф по Индии',
    'Prepare acquiring responsibilities, business category, merchant identity and integration questions for an India partner discussion.',
    'Подготовьте вопросы об эквайринге, категории бизнеса, идентификаторах мерчанта и интеграции для партнёра в Индии.',
    'provider',
    'india',
    ['npci'],
    [
      section(
        'acquiring',
        'Identify the acquiring relationship',
        'Определите отношения с эквайером',
        'NPCI’s merchant FAQ describes merchant acceptance through an acquiring bank. In a prospective partner discussion, ask which entity provides that relationship, who contracts with the merchant and who handles onboarding. Identify whether the proposed partner is the acquirer, an integration provider or an introducer. Request documents relevant to that actual role. The existence of UPI infrastructure does not confirm eligibility for a particular business category, and this guide does not establish PAN’s ability to process UPI payments.',
        'В FAQ NPCI приём UPI мерчантом описан через банк-эквайер. У потенциального партнёра уточните, кто предоставляет эту связь, заключает договор и проводит подключение. Определите его роль: эквайер, интегратор или посредник знакомства. Запросите относящиеся к роли документы. Наличие инфраструктуры UPI не подтверждает допустимость конкретной категории бизнеса; руководство не устанавливает возможность PAN проводить такие платежи.',
      ),
      section(
        'category',
        'Write down the business category and identity',
        'Зафиксируйте категорию и идентификаторы',
        'Describe the actual goods or services, website, contracting entity and operating markets. Ask the prospective acquirer how the business is classified and which identifiers appear in requests and reports. Clarify who owns the merchant configuration and who authorizes changes. Avoid substituting a broad label such as high risk for a concrete description of the business. Send sensitive documentation through the partner’s agreed secure channel after the initial fit has been established.',
        'Опишите товары или услуги, сайт, сторону договора и страны работы. Уточните классификацию бизнеса и идентификаторы в запросах и отчётах. Зафиксируйте владельца настройки мерчанта и порядок её изменения. Общее обозначение high risk не заменяет точного описания бизнеса. Чувствительные документы передавайте по согласованному защищённому каналу после проверки первоначального соответствия.',
      ),
      section(
        'tests',
        'Prepare an integration test plan',
        'Подготовьте план проверки интеграции',
        'Ask which integration modes are available to the proposed merchant and what the production approval path involves. Test transaction creation, customer abandonment, final status retrieval, callbacks and retries in a permitted test environment. Agree how a payment is matched to an order and how unsettled or disputed entries are investigated. Include these questions in the PAN partner brief so a first conversation can focus on specific responsibilities and evidence rather than a generic request for India coverage.',
        'Уточните доступные мерчанту режимы интеграции и порядок допуска в рабочую среду. В разрешённой тестовой среде проверьте создание операции, отказ клиента, конечный статус, уведомления и повторы. Согласуйте связь платежа с заказом и расследование спорных записей. Включите эти вопросы в бриф PAN, чтобы первый разговор касался ответственности и подтверждений.',
      ),
    ],
    [
      'Name the acquirer and contracting entity.',
      'Describe the actual business category.',
      'Confirm merchant configuration ownership.',
      'Request the test and production approval process.',
      'Define payment-to-order reconciliation.',
    ],
    [
      'Назовите эквайера и сторону договора.',
      'Опишите реальную категорию бизнеса.',
      'Определите владельца настройки мерчанта.',
      'Запросите порядок тестирования и запуска.',
      'Согласуйте сверку платежей с заказами.',
    ],
  ),
  base(
    'mpesa-daraja-integration-brief',
    'M-Pesa and Daraja: prepare a Kenya integration brief',
    'M-Pesa и Daraja: бриф для интеграции в Кении',
    'Separate collection, disbursement, credentials and callbacks when evaluating an M-Pesa integration partner.',
    'Разделите приём, выплаты, доступы и уведомления при оценке партнёра по интеграции M-Pesa.',
    'team',
    'kenya',
    ['daraja'],
    [
      section(
        'flows',
        'Select the required flow',
        'Выберите нужный поток',
        'Safaricom’s Daraja catalogue lists distinct collection, disbursement and authorization APIs. Start by describing whether you need customer collection, business payouts or both. Identify the contracting business and the party controlling the account and credentials. Do not treat a successful API demonstration as evidence that the proposed operating arrangement has been approved. Ask the partner to explain which products and permissions apply to the exact flow you intend to use.',
        'В каталоге Daraja Safaricom разделены API приёма, выплат и авторизации. Опишите, нужны ли платежи клиентов, выплаты бизнеса или оба потока. Укажите сторону договора и владельца аккаунта и доступов. Успешная демонстрация API не подтверждает одобрение предложенной схемы работы. Попросите объяснить, какие продукты и разрешения относятся к вашему потоку.',
      ),
      section(
        'credentials',
        'Keep access and responsibilities explicit',
        'Определите доступы и ответственность',
        'Ask who provisions the application, where credentials are stored, how access is rotated and which people can change callback endpoints. Keep production credentials out of an introductory message or shared brief. Agree how sandbox testing relates to the production setup and who signs off the transition. Confirm the business category and account arrangement directly with the relevant parties; an integration guide cannot replace that confirmation. Record outstanding permissions as open questions.',
        'Уточните, кто создаёт приложение, хранит и обновляет доступы и меняет адреса уведомлений. Рабочие ключи не включайте в знакомство или общий бриф. Согласуйте связь тестовой и рабочей среды и ответственного за запуск. Категорию бизнеса и схему аккаунта подтверждайте с соответствующими сторонами. Неопределённые разрешения фиксируйте как открытые вопросы.',
      ),
      section(
        'callbacks',
        'Test the evidence returned by the flow',
        'Проверьте подтверждения операции',
        'Walk through request identifiers, asynchronous notifications and final status checks. Test a delayed callback and a repeated request, and agree which system is authoritative when records disagree. Ask how collection and payout records appear in exports and how an incident reaches the operating team. In a PAN introduction, describe your actual experience, market, methods and operating responsibility. This provides context for a conversation without promising an unverified M-Pesa arrangement or a particular processing capacity.',
        'Проверьте идентификаторы запросов, асинхронные уведомления и конечные статусы. Испытайте задержку уведомления и повтор, согласуйте источник итогового состояния при расхождении записей. Уточните отображение приёма и выплат в отчётах и путь инцидента к команде. Для PAN опишите действительный опыт, рынок, методы и ответственность; это не обещание неподтверждённой схемы M-Pesa или мощности.',
      ),
    ],
    [
      'Specify collection, disbursement or both.',
      'Identify account and credential ownership.',
      'Confirm category and production permissions.',
      'Test asynchronous callbacks and retries.',
      'Agree reports and incident ownership.',
    ],
    [
      'Укажите приём, выплаты или оба потока.',
      'Определите владельцев аккаунта и доступов.',
      'Подтвердите категорию и разрешения.',
      'Проверьте уведомления и повторы.',
      'Согласуйте отчёты и инциденты.',
    ],
  ),
  base(
    'spei-payment-reference-brief',
    'SPEI payment partners: prepare references and reconciliation for Mexico',
    'Партнёры SPEI: идентификаторы и сверка в Мексике',
    'Prepare a Mexico bank-transfer discussion with clear participant roles, transfer evidence and exception ownership.',
    'Подготовьте обсуждение переводов в Мексике: роли участников, подтверждения платежей и ответственность за исключения.',
    'provider',
    'mexico',
    ['spei'],
    [
      section(
        'participants',
        'Explain the proposed participant relationship',
        'Опишите отношения участников',
        'Banco de México describes SPEI as an interbank electronic transfer system that it operates. Ask a prospective partner to explain its role in the transfer path and the financial institution involved. Identify the contracting entity, recipient arrangement and currency. A reference to SPEI alone does not explain who provides the service or what businesses can use the proposed arrangement. Confirm those details with the relevant parties before treating a Mexico payment brief as an integration plan.',
        'Banco de México описывает SPEI как межбанковскую систему электронных переводов под своим управлением. Попросите партнёра объяснить роль в цепочке и участвующую финансовую организацию. Укажите сторону договора, получателя и валюту. Название SPEI само по себе не объясняет поставщика услуги или доступность схемы для бизнеса. Подтвердите эти сведения до подготовки интеграции.',
      ),
      section(
        'references',
        'Map transfer evidence to the merchant order',
        'Свяжите перевод с заказом',
        'Ask which payment reference or trace identifier the provider returns and how it relates to an order. Request an example using fictitious account information. Define what the operator should collect when a payment cannot be found, who can investigate it and which evidence supports the final decision. Avoid putting real customer account details in a public introduction. Keep the transfer record and the commercial settlement entry distinguishable so an adjustment can be explained without losing the original evidence.',
        'Уточните идентификатор или референс перевода и его связь с заказом. Запросите пример с тестовыми реквизитами. Определите данные для поиска пропавшего платежа, ответственного за расследование и подтверждения конечного решения. Реальные реквизиты клиентов не включайте в публичное знакомство. Запись перевода и коммерческого расчёта должны различаться, чтобы корректировка сохраняла исходное подтверждение.',
      ),
      section(
        'exceptions',
        'Agree the exception workflow',
        'Согласуйте обработку исключений',
        'Discuss unmatched transfers, repeated customer payments, delayed notifications and report corrections. Agree the reporting timezone, export fields and escalation contact. Request a sample reconciliation file before comparing commercials, because an unclear operating flow can hide important work. In a PAN provider introduction, state the market and your actual responsibility in the proposed flow. PAN reviews introductions individually; this preparation guide does not confirm capacity, settlement terms or support for a particular business category.',
        'Обсудите неопознанные переводы, повторы клиентов, задержки уведомлений и исправления отчётов. Согласуйте часовой пояс, поля выгрузки и контакт эскалации. Запросите пример сверки до сравнения коммерческих условий. В знакомстве через PAN укажите рынок и свою реальную роль. PAN рассматривает обращения отдельно; руководство не подтверждает мощность, условия расчётов или поддержку категории.',
      ),
    ],
    [
      'Identify the participant and contracting entity.',
      'Map transfer references to orders.',
      'Define evidence for unmatched payments.',
      'Request a reconciliation sample.',
      'Agree responsibility for corrections and incidents.',
    ],
    [
      'Укажите участника и сторону договора.',
      'Свяжите идентификаторы переводов с заказами.',
      'Определите данные для неопознанных платежей.',
      'Запросите пример сверки.',
      'Согласуйте ответственность за исправления и инциденты.',
    ],
  ),
];

export const staticRoutes = [
  '/',
  '/affiliates',
  '/teams',
  '/payment-partners',
  '/merchants',
  '/markets',
  '/about',
  '/apply',
  '/privacy',
  '/terms',
  '/knowledge',
  ...[
    'india',
    'ghana',
    'kenya',
    'peru',
    'colombia',
    'uganda',
    'tanzania',
    'nigeria',
    'mexico',
    'south-africa',
  ].map((slug) => '/markets/' + slug),
];
